# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 14:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserManager', '0002_customermessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='companyName',
            field=models.TextField(verbose_name='نام شرکت'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='moaref',
            field=models.CharField(max_length=200, verbose_name='نام معرف'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phoneNumber',
            field=models.CharField(max_length=50, verbose_name='شماره تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='workPhoneNumber',
            field=models.CharField(max_length=50, verbose_name='تلفن محل کار'),
        ),
        migrations.AlterField(
            model_name='customermessage',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.Customer', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='customermessage',
            name='message',
            field=models.TextField(verbose_name='نامه'),
        ),
        migrations.AlterField(
            model_name='kargar',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
    ]
