# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0005_auto_20161028_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'مشتری'},
        ),
        migrations.AlterModelOptions(
            name='customermessage',
            options={'verbose_name_plural': 'پیام مشتری'},
        ),
        migrations.AlterModelOptions(
            name='kargar',
            options={'verbose_name_plural': 'کارگر'},
        ),
    ]
