# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0012_auto_20161205_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customermessage',
            options={},
        ),
        migrations.AlterField(
            model_name='customermessage',
            name='message',
            field=models.TextField(verbose_name='متن نامه'),
        ),
    ]
