# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0014_event_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
    ]
