# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0015_remove_customer_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customermessage',
            options={'verbose_name_plural': 'پیام مشتری'},
        ),
        migrations.AlterField(
            model_name='customermessage',
            name='message',
            field=models.TextField(verbose_name='نامه'),
        ),
    ]
