# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0016_auto_20161207_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='code',
            field=models.IntegerField(default=0, verbose_name='کد'),
        ),
    ]
