# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 18:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0021_adminsite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminsite',
            options={'verbose_name': 'ادمین', 'verbose_name_plural': 'ادمین'},
        ),
        migrations.AlterField(
            model_name='adminsite',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
