# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0022_auto_20170105_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='companyName',
            field=models.CharField(max_length=100, verbose_name='نام شرکت'),
        ),
    ]
