# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0023_auto_20170105_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='companyName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام شرکت'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='moaref',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام معرف'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=100, verbose_name='نام کاربری'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='workPhoneNumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تلفن محل کار'),
        ),
    ]
