# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0026_auto_20170114_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermessage',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ'),
        ),
        migrations.AddField(
            model_name='customermessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده'),
        ),
    ]
