# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dookht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('duration', models.IntegerField()),
                ('kargar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.Kargar')),
            ],
        ),
        migrations.CreateModel(
            name='ReserveForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarh', models.ImageField(upload_to='tarh/')),
                ('hasParche', models.BooleanField()),
                ('sizeX', models.FloatField()),
                ('sizeY', models.FloatField()),
                ('hasLabel', models.BooleanField()),
                ('reserveDay', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)])),
                ('reserveMonth', models.IntegerField(choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')])),
                ('reserveYear', models.IntegerField()),
                ('deliveryDay', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)])),
                ('deliveryMonth', models.IntegerField(choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')])),
                ('deliveryYear', models.IntegerField()),
                ('description', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.Customer')),
                ('parche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReserveForm.Parche')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReserveForm.Process')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTarh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='reserveform',
            name='serviceTarh',
            field=models.ManyToManyField(to='ReserveForm.ServiceTarh'),
        ),
        migrations.AddField(
            model_name='reserveform',
            name='typeChap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReserveForm.Chap'),
        ),
    ]
