# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0001_initial'),
        ('ReserveForm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessFormKargar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReserveForm.ReserveForm')),
                ('kargar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.Kargar')),
            ],
        ),
        migrations.RemoveField(
            model_name='process',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='process',
            name='kargar',
        ),
        migrations.AddField(
            model_name='processformkargar',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReserveForm.Process'),
        ),
    ]
