# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReserveForm', '0002_auto_20161026_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserveform',
            old_name='sizeX',
            new_name='parcheHeighet',
        ),
        migrations.RenameField(
            model_name='reserveform',
            old_name='sizeY',
            new_name='parcheWidth',
        ),
    ]
