# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReserveForm', '0003_auto_20161026_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserveform',
            old_name='parcheHeighet',
            new_name='parcheHeight',
        ),
    ]
