# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReserveForm', '0004_auto_20161026_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserveform',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
