# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReserveForm', '0005_reserveform_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chap',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='chap',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='dookht',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='dookht',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='parche',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='parche',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.TextField(verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='processformkargar',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReserveForm.ReserveForm', verbose_name='فرم'),
        ),
        migrations.AlterField(
            model_name='processformkargar',
            name='kargar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.Kargar', verbose_name='کارگر'),
        ),
        migrations.AlterField(
            model_name='processformkargar',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReserveForm.Process', verbose_name='فرایند'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManager.Customer', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='deliveryDay',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], verbose_name='روز'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='deliveryMonth',
            field=models.IntegerField(choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], verbose_name='ماه'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='deliveryYear',
            field=models.IntegerField(verbose_name='سال'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='description',
            field=models.TextField(verbose_name='توضیح'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='hasLabel',
            field=models.BooleanField(verbose_name='برچسب دارد'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='hasParche',
            field=models.BooleanField(verbose_name='پارچه دارد'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='number',
            field=models.IntegerField(null=True, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='parche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReserveForm.Parche', verbose_name='پارچه'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='parcheHeight',
            field=models.FloatField(verbose_name='طول پارچه'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='parcheWidth',
            field=models.FloatField(verbose_name='عرض پارچه'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReserveForm.Process', verbose_name='فرایند'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='reserveDay',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], verbose_name='روز'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='reserveMonth',
            field=models.IntegerField(choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], verbose_name='ماه'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='reserveYear',
            field=models.IntegerField(verbose_name='سال'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='serviceTarh',
            field=models.ManyToManyField(to='ReserveForm.ServiceTarh', verbose_name='خدمات طرح'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='tarh',
            field=models.ImageField(upload_to='tarh/', verbose_name='طرح'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='typeChap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReserveForm.Chap', verbose_name='چاپ'),
        ),
        migrations.AlterField(
            model_name='servicetarh',
            name='name',
            field=models.TextField(verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='servicetarh',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
    ]
