# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReserveForm', '0008_auto_20161115_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='processformkargar',
            name='endDay',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], null=True, verbose_name='روز'),
        ),
        migrations.AddField(
            model_name='processformkargar',
            name='endMonth',
            field=models.IntegerField(blank=True, choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], null=True, verbose_name='ماه'),
        ),
        migrations.AddField(
            model_name='processformkargar',
            name='endYear',
            field=models.IntegerField(blank=True, choices=[(1395, '۱۳۹۵'), (1396, '۱۳۹۶'), (1397, '۱۹۳۷'), (1398, '۱۳۹۸'), (1399, '۱۳۹۹'), (1400, '۱۴۰۰'), (1401, '۱۴۰۱'), (1402, '۱۴۰۲'), (1403, '۱۴۰۳'), (1404, '۱۴۰۴'), (1405, '۱۴۰۵')], null=True, verbose_name='سال'),
        ),
        migrations.AddField(
            model_name='processformkargar',
            name='startDay',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], null=True, verbose_name='روز'),
        ),
        migrations.AddField(
            model_name='processformkargar',
            name='startMonth',
            field=models.IntegerField(blank=True, choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], null=True, verbose_name='ماه'),
        ),
        migrations.AddField(
            model_name='processformkargar',
            name='startYear',
            field=models.IntegerField(blank=True, choices=[(1395, '۱۳۹۵'), (1396, '۱۳۹۶'), (1397, '۱۹۳۷'), (1398, '۱۳۹۸'), (1399, '۱۳۹۹'), (1400, '۱۴۰۰'), (1401, '۱۴۰۱'), (1402, '۱۴۰۲'), (1403, '۱۴۰۳'), (1404, '۱۴۰۴'), (1405, '۱۴۰۵')], null=True, verbose_name='سال'),
        ),
        migrations.AlterField(
            model_name='dookht',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='parche',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='dookht',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ReserveForm.Dookht', verbose_name='دوخت'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='parche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ReserveForm.Parche', verbose_name='پارچه'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='parcheHeight',
            field=models.FloatField(blank=True, null=True, verbose_name='طول پارچه'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='parcheWidth',
            field=models.FloatField(blank=True, null=True, verbose_name='عرض پارچه'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ReserveForm.Process', verbose_name='فرایند'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='reserveDay',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], null=True, verbose_name='روز'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='reserveMonth',
            field=models.IntegerField(blank=True, choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], null=True, verbose_name='ماه'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='reserveYear',
            field=models.IntegerField(blank=True, null=True, verbose_name='سال'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='serviceTarh',
            field=models.ManyToManyField(to='ReserveForm.ServiceTarh', verbose_name='خدمات طرح'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='tarh',
            field=models.ImageField(blank=True, null=True, upload_to='tarh/', verbose_name='طرح'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='typeChap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ReserveForm.Chap', verbose_name='چاپ'),
        ),
        migrations.AlterField(
            model_name='servicetarh',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
    ]
