# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReserveForm', '0011_reserveform_testtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserveform',
            name='testtime',
        ),
    ]
