# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReserveForm', '0013_auto_20161205_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
