# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReserveForm', '0014_auto_20161205_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='processformkargar',
            name='rate',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='امتیاز کارگر'),
        ),
    ]
