# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReserveForm', '0015_processformkargar_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserveform',
            name='code',
            field=models.IntegerField(default=0, verbose_name='کد'),
        ),
    ]
