# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReserveForm', '0018_auto_20161225_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('price', models.IntegerField(verbose_name='قیمت')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.AlterModelOptions(
            name='chap',
            options={'verbose_name': 'چاپ', 'verbose_name_plural': 'چاپ'},
        ),
        migrations.AlterModelOptions(
            name='dookht',
            options={'verbose_name': 'دوخت', 'verbose_name_plural': 'دوخت'},
        ),
        migrations.AlterModelOptions(
            name='parche',
            options={'verbose_name': 'پارچه', 'verbose_name_plural': 'پارچه'},
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name': 'فرایند', 'verbose_name_plural': 'فرایند'},
        ),
        migrations.AlterModelOptions(
            name='processformkargar',
            options={'verbose_name': 'وضعیت سفارش', 'verbose_name_plural': 'وضعیت سفارش'},
        ),
        migrations.AlterModelOptions(
            name='reserveform',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش'},
        ),
        migrations.AlterModelOptions(
            name='servicetarh',
            options={'verbose_name': ' خدمات مربوط به طرح', 'verbose_name_plural': ' خدمات مربوط به طرح'},
        ),
        migrations.AlterField(
            model_name='processformkargar',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReserveForm.ReserveForm', verbose_name='کد سفارش'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='hasLabel',
            field=models.BooleanField(verbose_name='لیبل دارد'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='process',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='ReserveForm.Process', verbose_name='فرایند'),
        ),
        migrations.AddField(
            model_name='reserveform',
            name='otherServices',
            field=models.ManyToManyField(blank=True, to='ReserveForm.OtherServices', verbose_name='سایر خدمات'),
        ),
    ]
