# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReserveForm', '0019_auto_20161228_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otherservices',
            options={'verbose_name': 'سایر خدمات', 'verbose_name_plural': 'سایر خدمات'},
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='parcheHeight',
            field=models.IntegerField(blank=True, null=True, verbose_name='طول پارچه'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='parcheWidth',
            field=models.IntegerField(blank=True, null=True, verbose_name='عرض پارچه'),
        ),
    ]
