# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReserveForm', '0020_auto_20161231_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processformkargar',
            name='kargar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserManager.Kargar', verbose_name='کارگر'),
        ),
    ]
