# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReserveForm', '0021_auto_20170124_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveform',
            name='deliveryYear',
            field=models.IntegerField(blank=True, choices=[(1395, '۱۳۹۵'), (1396, '۱۳۹۶'), (1397, '۱۹۳۷'), (1398, '۱۳۹۸'), (1399, '۱۳۹۹'), (1400, '۱۴۰۰'), (1401, '۱۴۰۱'), (1402, '۱۴۰۲'), (1403, '۱۴۰۳'), (1404, '۱۴۰۴'), (1405, '۱۴۰۵')], null=True, verbose_name='سال'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='hasLabel',
            field=models.BooleanField(default=False, verbose_name='لیبل دارد'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='hasParche',
            field=models.BooleanField(default=False, verbose_name='پارچه دارد'),
        ),
        migrations.AlterField(
            model_name='reserveform',
            name='reserveYear',
            field=models.IntegerField(blank=True, choices=[(1395, '۱۳۹۵'), (1396, '۱۳۹۶'), (1397, '۱۹۳۷'), (1398, '۱۳۹۸'), (1399, '۱۳۹۹'), (1400, '۱۴۰۰'), (1401, '۱۴۰۱'), (1402, '۱۴۰۲'), (1403, '۱۴۰۳'), (1404, '۱۴۰۴'), (1405, '۱۴۰۵')], null=True, verbose_name='سال'),
        ),
    ]
